filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/*.log
  fields:
    log_type: spring-boot
  fields_under_root: false
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/app/access.log
  fields:
    log_type: access
  fields_under_root: false

- type: log
  enabled: true
  paths:
    - /var/log/app/business.log
  fields:
    log_type: business
  fields_under_root: false

- type: log
  enabled: true
  paths:
    - /var/log/app/error.log
  fields:
    log_type: error
  fields_under_root: false

output.logstash:
  hosts: ["logstash:5044"]

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
